Repository bitcoin-s/krystal-bull, pull requests merged in 2021-06, with the labels that each got.

#68 Specify teamid when notarizing on mac
  .github/workflows/release.yml
Labels: build

#69 Oracle Explorer confirmation
  project/Deps.scala
  project/build.properties
  src/main/resources/icons/green-check.png
  src/main/resources/icons/red-x.png
  src/main/scala/com/krystal/bull/gui/GUI.scala
  src/main/scala/com/krystal/bull/gui/dialog/ViewEventDialog.scala
  src/main/scala/com/krystal/bull/gui/home/HomePane.scala
Labels: enhancement

#72 Open link on click
  src/main/scala/com/krystal/bull/gui/dialog/ViewEventDialog.scala
Labels: bug

#76 Fix not sending sigs
  project/Deps.scala
  src/main/scala/com/krystal/bull/gui/dialog/ViewEventDialog.scala
Labels: bug
